### ISSUE TITLE
Crash in _canonicalPath(), on iOS 9 (DB22)

### ISSUE THREAD

**Issue by jayzhanghs** [couchbase/couchbase-lite-ios#2097]
EXC_BAD_ACCESS on iOS 9

Stack trace:

<img width="695" alt="screen shot 2018-03-13 at 10 26 39 am" src="https://user-images.githubusercontent.com/18294900/37347836-2056f3f4-26a9-11e8-8850-c2ada05a796e.png">

This crash repeats every time.

--------
* Version:   DB22+
* Client OS: iOS 9
* Server:    SG 2.0

**Comment by snej** [comment]
(Just FYI, you can get a textual backtrace by typing `bt` at the debugger prompt. Then paste it in with a line of three back-quote characters above and below it. This is more readable and searchable than a screenshot.)

**Comment by snej** [comment]
What's the memory address of the bad access?

**Comment by snej** [comment]
Figured it out: `kCFURLCanonicalPathKey` is only available on iOS 10 (and macOS 10.12) or later :(
```
CF_EXPORT
const CFStringRef kCFURLCanonicalPathKey API_AVAILABLE(macosx(10.12), ios(10.0), watchos(3.0), tvos(10.0));
```

**Comment by snej** [comment]
This was introduced by 6341c8f on 1/31, to fix problems opening databases on different but equivalent paths. We need a workaround to get the canonical version of a path (resolving symlinks).

**Comment by snej** [comment]
(Note: fix will not be available until iOS updates its LiteCore submodule.)

**Comment by jayzhanghs** [comment]
how will we be notified when LiteCore submodule is updated? In this thread?

**Comment by pasin** [comment]
Updated

**Comment by jayzhanghs** [comment]
it still crashed in iOS 9, at a place other than cononicalPath

https://gist.github.com/jayzhanghs/326da343d1950d849f126328a8745fae

**Comment by pasin** [comment]
In additional to the gist above, here is the dyld error when I ran replication test with iOS9.

```
dyld: Symbol not found: _dispatch_queue_attr_make_with_autorelease_frequency
```

**Comment by jayzhanghs** [comment]
Thanks @pasin . We still have a significant percentage of users on iOS 9.

**Comment by snej** [comment]
I've just enabled `-Wunguarded-availability` in LiteCore (it was already enabled in CBL) and it detected both of these problems. The second one is due to use of the symbol `DISPATCH_AUTORELEASE_FREQUENCY_NEVER` in the replicator, which is also only available in iOS 10+. I'm adding a runtime check for it using `__builtin_available()`.

**Comment by jayzhanghs** [comment]
Is this fix pushed to the master now?

**Comment by snej** [comment]
It is now, as of about 30 seconds ago :)

**Comment by jayzhanghs** [comment]
Compiled with latest pull and build (head at 2b7b37b3f9a9e), but still crashed in iOS 9 with EXC_BREAKPOINT, at another different place: 

https://gist.github.com/jayzhanghs/e7c84df1d3c71d49fbff45f2c7ff35f7

**Comment by snej** [comment]
Another dyld missing symbol, in something called by `litecore::blip::MessageOut::nextFrameToSend`.
There should have been a message logged by dyld about what the missing symbol is?

**Comment by jayzhanghs** [comment]
like this?

```
dyld: lazy symbol binding failed: Symbol not found: _deflatePending
  Referenced from: /Users/jayzhang/Library/Developer/CoreSimulator/Devices/D3688125-182A-4CFB-A7CA-09F0C977CAB7/data/Containers/Bundle/Application/C7868412-87CF-418C-BB9C-D5B06452F4CE/companyNameHD.app/Frameworks/CouchbaseLiteSwift.framework/CouchbaseLiteSwift
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 9.3.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libz.1.dylib

dyld: Symbol not found: _deflatePending
  Referenced from: /Users/jayzhang/Library/Developer/CoreSimulator/Devices/D3688125-182A-4CFB-A7CA-09F0C977CAB7/data/Containers/Bundle/Application/C7868412-87CF-418C-BB9C-D5B06452F4CE/companyNameHD.app/Frameworks/CouchbaseLiteSwift.framework/CouchbaseLiteSwift
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 9.3.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libz.1.dylib
```

**Comment by snej** [comment]
Exactly, thanks. Looks like this zlib function is new-ish, and the version of zlib was upgraded in the iOS 10 timeframe:

```C
ZEXTERN int ZEXPORT deflatePending OF((z_streamp strm,
                                       unsigned *pending,
                                       int *bits))
__OSX_AVAILABLE_STARTING(__MAC_10_10,__IPHONE_8_0);
```

**Comment by snej** [comment]
Closing this since the actual error is in LiteCore, and the culprit is no longer canonicalPath().
